### PR TITLE
add Microsoft as sponsor

### PR DESCRIPTION
**Pull request by alexsavio**

### CODE REVIEW

**Comment by pdebuyl** [comment]
and published (the change was not online)

**Comment by datapythonista** [comment]
sorry, was too tired to deploy it yesterday when I merged (the permissions and group in the server change every time you publish, and takes me a significant amount of time to do the deployments, most of the times I end up updating file by file)

**Comment by pdebuyl** [comment]
I thought the permissions were ok since I added the group euroscipyweb. I'll check the settings.

**Comment by datapythonista** [comment]
when you sync the group of the files changes to your user group, and I think the writing permissions for the group are also lost

wanted to look at it myself, but forgot how to set up those things, and don't have much time either

thanks!

**Comment by alexsavio** [comment]
if you send me the static pages that are in the server, we could start the migration to the github pages, during the conference sprints.

**Comment by pdebuyl** [comment]
I added the option `--chown=:euroscipyweb` to the Makefile. Let me know if the issue is resolved.

**Comment by datapythonista** [comment]
ok, will let you know the next push. Did you updated the current permissions? I can do that when I do the next deployment.

Thank you!

@alexsavio I can download the files from the server, I think we just need to copy them as if they were static files, and set up pelican to copy them with the static files (but in their directories, not in static)

**Comment by alexsavio** [comment]
@datapythonista sure, we can figure out later how to organize it, I guess?

**Comment by datapythonista** [comment]
We managed to make it much simpler to deploy now, see #93.

If that is merged, my preference would be to create a user in the server for you, one for the CI job, and with that it takes me 10 minutes to trigger the deploys from the CI.

@pdebuyl what do you think?

**Pull request merged**
