### PR TITLE
Adding maintainers and sponsorhip info pages

### PR DESCRIPTION
**Pull request by datapythonista**
Rendered the result in: http://datapythonista.github.io/docs/www.euroscipy.org/2019/

See mainly:
- http://datapythonista.github.io/docs/www.euroscipy.org/2019/sponsors_info.html
- http://datapythonista.github.io/docs/www.euroscipy.org/2019/maintainers.html

### CODE REVIEW

**Comment by pdebuyl** [comment]
Let me know when I can merge and publish.

P

**Comment by drsavio** [comment]
LGTM. Thanks!

**Comment by datapythonista** [comment]
amazing, the new email is also working, @pdebuyl can you merge please?

**Comment by pdebuyl** [comment]
Online :-)

**Comment by datapythonista** [comment]
amazing, thanks a lot!

**Pull request merged**
