### PR TITLE
capital month names; removed redundant headers

### PR DESCRIPTION
**Pull request by mimuellerPyA**

### CODE REVIEW

**Comment by pdebuyl** [comment]
Is the removal of the link to the YouTube channel intentional?

**Comment by mimuellerPyA** [comment]
No, it isn't... I think it is because I moved it to a separate section, but I can move it back up if that is better

**Comment by pdebuyl** [comment]
sorry, I didn't see it was below.

**Comment by mimuellerPyA** [comment]
However, I can't run the make script without the following error message:
``WARNING: Feeds generated without SITEURL set properly may not be valid
ERROR: Skipping pages/2017/descriptions/index.md: could not find information about 'title'``

**Comment by pdebuyl** [comment]
The warning

    WARNING: Feeds generated without SITEURL set properly may not be valid

only occurs when building the website locally (i.e. "make html"). It is not present when running "make rsync".

The error

    ERROR: Skipping pages/2017/descriptions/index.md: could not find information about 'title'

occurs because of a useless file. I guess we can remove it.

**Pull request merged**
